

rm(list=ls())

library(sp)
library(raster)
library(spatstat)
library(maptools)
library(shapefiles)

setwd("C:\\Users\\richard.hedger\\OneDrive - NINA\\")
source("NINA projects\\TruaArter\\Code\\Functions\\lso.r")
source("NINA projects\\TruaArter\\Code\\Functions\\myPseudoR2.r")
source("NINA projects\\TruaArter\\Code\\Functions\\gbifJitter.r")
source("NINA projects\\TruaArter\\Code\\Functions\\predPlot.r")
source("NINA projects\\TruaArter\\Code\\Functions\\multiCoefPlot.r")

#setwd("R:/Prosjekter/15801000_geografisk_utbredelse_av_trua_arter_i_norge/GIS")
setwd("C:/GIS")

load("Basic_data\\Borders\\NorwayCounty.Rdata")
NorwayBorder <- rgeos::gUnaryUnion(NorwayCounty)

#D.1km<-raster(paste0("Biophysical_variables\\NDVI_1km_updated.tif"))
D.1km<-raster(paste0("Biophysical_variables\\temperature_1km.tif"))
plot(D.1km,xlim=c(7e+05,10e+05),ylim=c(7500000,8000000),col=rainbow(10))
D.1km<-mask(D.1km,NorwayBorder)
plot(D.1km,xlim=c(7e+05,10e+05),ylim=c(7500000,8000000),col=rainbow(10)); plot(NorwayBorder,add=TRUE)
D.1km<-as.im.RasterLayer(D.1km)
plot(D.1km,xlim=c(7e+05,10e+05),ylim=c(7500000,8000000))
NorWin.1km <- as.owin(D.1km, "owin")

save(NorWin.1km, file="Rdata\\NorWin.1km.Rdata")

Alt.1km<-raster(paste0("Biophysical_variables\\altitude_1km_updated.tif"))
Alt.1km<-mask(Alt.1km,NorwayBorder)
Alt.1km<-as.im.RasterLayer(Alt.1km)
Alt.1km<-as.im(Alt.1km,NorWin.1km)
save(Alt.1km, file="Rdata\\Alt.1km.Rdata")
plot(Alt.1km)
rm(Alt.1km)

Calc.1km<-raster(paste0("Biophysical_variables\\calciferous_1km.tif"))
Calc.1km<-mask(Calc.1km,NorwayBorder)
Calc.1km<-as.im.RasterLayer(Calc.1km)
Calc.1km<-as.im(Calc.1km,NorWin.1km)
save(Calc.1km, file="Rdata\\Calc.1km.Rdata")
plot(Calc.1km)
rm(Calc.1km)

NDVI.1km<-raster(paste0("Biophysical_variables\\NDVI_1km_updated.tif"))
NDVI.1km<-mask(NDVI.1km,NorwayBorder)
NDVI.1km<-as.im.RasterLayer(NDVI.1km)
NDVI.1km<-as.im(NDVI.1km,NorWin.1km)
save(NDVI.1km, file="Rdata\\NDVI.1km.Rdata")
plot(NDVI.1km)
rm(NDVI.1km)

Spr.1km<-raster(paste0("Biophysical_variables\\onsetOfSpring_1km.tif"))
Spr.1km<-mask(Spr.1km,NorwayBorder)
Spr.1km<-as.im.RasterLayer(Spr.1km)
Spr.1km<-as.im(Spr.1km,NorWin.1km)
save(Spr.1km, file="Rdata\\Spr.1km.Rdata")
plot(Spr.1km)
rm(Spr.1km)

PPT.1km<-raster(paste0("Biophysical_variables\\precipitation_1km.tif"))
PPT.1km<-mask(PPT.1km,NorwayBorder)
PPT.1km<-as.im.RasterLayer(PPT.1km)
PPT.1km<-as.im(PPT.1km,NorWin.1km)
save(PPT.1km, file="Rdata\\PPT.1km.Rdata")
plot(PPT.1km)
rm(PPT.1km)

Snow.1km<-raster(paste0("Biophysical_variables\\snowCover_1km_updated.tif"))
Snow.1km<-mask(Snow.1km,NorwayBorder)
Snow.1km<-as.im.RasterLayer(Snow.1km)
Snow.1km<-as.im(Snow.1km,NorWin.1km)
save(Snow.1km, file="Rdata\\Snow.1km.Rdata")
plot(Snow.1km)
rm(Snow.1km)

Sol.1km<-raster(paste0("Biophysical_variables\\solarRadiation_1km_updated.tif"))
Sol.1km<-mask(Sol.1km,NorwayBorder)
Sol.1km<-as.im.RasterLayer(Sol.1km)
Sol.1km<-as.im(Sol.1km,NorWin.1km)
save(Sol.1km, file="Rdata\\Sol.1km.Rdata")
plot(Sol.1km)
rm(Sol.1km)

Temp.1km<-raster(paste0("Biophysical_variables\\temperature_1km.tif"))
CRS<-crs(Temp.1km)
Temp.1km<-mask(Temp.1km,NorwayBorder)
Temp.1km<-as.im.RasterLayer(Temp.1km)
Temp.1km<-as.im(Temp.1km,NorWin.1km)
save(Temp.1km, file="Rdata\\Temp.1km.Rdata")
plot(Temp.1km)
rm(Temp.1km)

Land.1km<-raster(paste0("Anthropogenic_variables\\ar5_landuse_1km.tif"))
Land.1km<-projectRaster(Land.1km, crs=CRS)
Land.1km<-mask(Land.1km,NorwayBorder)
Land.1km<-as.im.RasterLayer(Land.1km)
Land.1km<-as.im(Land.1km,NorWin.1km)
save(Land.1km, file="Rdata\\Land.1km.Rdata")
plot(Land.1km)
rm(Land.1km)

Pop.1km<-raster(paste0("Anthropogenic_variables\\popDensity_1km.tif"))
Pop.1km<-projectRaster(Pop.1km, crs=CRS)
Pop.1km<-mask(Pop.1km,NorwayBorder)
Pop.1km<-as.im.RasterLayer(Pop.1km)
Pop.1km<-as.im(Pop.1km,NorWin.1km)
save(Pop.1km, file="Rdata\\Pop.1km.Rdata")
plot(Pop.1km)
rm(Pop.1km)

HerbDist.1km<-raster(paste0("Anthropogenic_variables\\herbaria_distance.tif"))
HerbDist.1km<-mask(HerbDist.1km,NorwayBorder)
HerbDist.1km<-as.im.RasterLayer(HerbDist.1km)
HerbDist.1km<-as.im(HerbDist.1km,NorWin.1km)
save(HerbDist.1km, file="Rdata\\HerbDist.1km.Rdata")
plot(HerbDist.1km)
rm(HerbDist.1km)

PortDist.1km<-raster(paste0("Anthropogenic_variables\\port_distance.tif"))
CRS.ini<-crs(PortDist.1km)
PortDist.1km<-as.im.RasterLayer(PortDist.1km)
PortDist.1km<-as.im(PortDist.1km,NorWin.1km)
PortDist.1km<-raster(PortDist.1km)
PortDist.1km<-mask(PortDist.1km,NorwayBorder)
crs(PortDist.1km)<-CRS.ini
PortDist.1km<-projectRaster(PortDist.1km, crs=CRS)
PortDist.1km<-as.im.RasterLayer(PortDist.1km)
PortDist.1km<-as.im(PortDist.1km,NorWin.1km)
save(PortDist.1km, file="Rdata\\PortDist.1km.Rdata")
plot(PortDist.1km)
rm(PortDist.1km)


RailDist.1km<-raster(paste0("Anthropogenic_variables\\railway_distance.tif"))
CRS.ini<-crs(RailDist.1km)
RailDist.1km<-as.im.RasterLayer(RailDist.1km)
RailDist.1km<-as.im(RailDist.1km,NorWin.1km)
RailDist.1km<-raster(RailDist.1km)
RailDist.1km<-mask(RailDist.1km,NorwayBorder)
crs(RailDist.1km)<-CRS.ini
RailDist.1km<-projectRaster(RailDist.1km, crs=CRS)
RailDist.1km<-as.im.RasterLayer(RailDist.1km)
RailDist.1km<-as.im(RailDist.1km,NorWin.1km)
save(RailDist.1km, file="Rdata\\RailDist.1km.Rdata")
plot(RailDist.1km)
rm(RailDist.1km)


RivDist.1km<-raster(paste0("Anthropogenic_variables\\river_distance.tif"))
CRS.ini<-crs(RivDist.1km)
RivDist.1km<-as.im.RasterLayer(RivDist.1km)
RivDist.1km<-as.im(RivDist.1km,NorWin.1km)
RivDist.1km<-raster(RivDist.1km)
RivDist.1km<-mask(RivDist.1km,NorwayBorder)
crs(RivDist.1km)<-CRS.ini
RivDist.1km<-projectRaster(RivDist.1km, crs=CRS)
RivDist.1km<-as.im.RasterLayer(RivDist.1km)
RivDist.1km<-as.im(RivDist.1km,NorWin.1km)
save(RivDist.1km, file="Rdata\\RivDist.1km.Rdata")
plot(RivDist.1km)
rm(RivDist.1km)


RoadDist.1km<-raster(paste0("Anthropogenic_variables\\road_distance.tif"))
CRS.ini<-crs(RoadDist.1km)
RoadDist.1km<-as.im.RasterLayer(RoadDist.1km)
RoadDist.1km<-as.im(RoadDist.1km,NorWin.1km)
RoadDist.1km<-raster(RoadDist.1km)
RoadDist.1km<-mask(RoadDist.1km,NorwayBorder)
crs(RoadDist.1km)<-CRS.ini
RoadDist.1km<-projectRaster(RoadDist.1km, crs=CRS)
RoadDist.1km<-as.im.RasterLayer(RoadDist.1km)
RoadDist.1km<-as.im(RoadDist.1km,NorWin.1km)
save(RoadDist.1km, file="Rdata\\RoadDist.1km.Rdata")
plot(RoadDist.1km)
rm(RoadDist.1km)

SettDist.1km<-raster(paste0("Anthropogenic_variables\\settlement_distance.tif"))
CRS.ini<-crs(SettDist.1km)
SettDist.1km<-as.im.RasterLayer(SettDist.1km)
SettDist.1km<-as.im(SettDist.1km,NorWin.1km)
SettDist.1km<-raster(SettDist.1km)
SettDist.1km<-mask(SettDist.1km,NorwayBorder)
crs(SettDist.1km)<-CRS.ini
SettDist.1km<-projectRaster(SettDist.1km, crs=CRS)
SettDist.1km<-as.im.RasterLayer(SettDist.1km)
SettDist.1km<-as.im(SettDist.1km,NorWin.1km)
save(SettDist.1km, file="Rdata\\SettDist.1km.Rdata")
plot(SettDist.1km)
rm(SettDist.1km)
